<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKveuaxe\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKveuaxe/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKveuaxe.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKveuaxe\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKveuaxe\appProdProjectContainer([
    'container.build_hash' => 'Kveuaxe',
    'container.build_id' => 'fa0c66d4',
    'container.build_time' => 1585300031,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKveuaxe');
